/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SupportRouteImport } from './routes/support'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AuthVerifyEmailRouteImport } from './routes/auth/verify-email'
import { Route as AuthenticatedNewsRouteImport } from './routes/_authenticated/news'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthSignUpIndexRouteImport } from './routes/auth/sign-up/index'
import { Route as AuthSignInIndexRouteImport } from './routes/auth/sign-in/index'
import { Route as AuthResetPasswordIndexRouteImport } from './routes/auth/reset-password/index'
import { Route as AuthForgotPasswordIndexRouteImport } from './routes/auth/forgot-password/index'
import { Route as AuthenticatedWalletIndexRouteImport } from './routes/_authenticated/wallet/index'
import { Route as AuthenticatedTransactionsIndexRouteImport } from './routes/_authenticated/transactions/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedNotificationsIndexRouteImport } from './routes/_authenticated/notifications/index'
import { Route as AuthenticatedInvestmentsIndexRouteImport } from './routes/_authenticated/investments/index'
import { Route as AuthenticatedFarmsIndexRouteImport } from './routes/_authenticated/farms/index'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedSettingsVerificationRouteImport } from './routes/_authenticated/settings/verification'
import { Route as AuthenticatedSettingsSecurityRouteImport } from './routes/_authenticated/settings/security'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedPaymentCallbackRouteImport } from './routes/_authenticated/payment/callback'
import { Route as AuthenticatedInvestmentsIdRouteImport } from './routes/_authenticated/investments/$id'
import { Route as AuthenticatedFarmIdRouteImport } from './routes/_authenticated/farm/$id'
import { Route as AuthenticatedAdminTransactionsRouteImport } from './routes/_authenticated/admin/transactions'
import { Route as AuthenticatedAdminReportsRouteImport } from './routes/_authenticated/admin/reports'
import { Route as AuthenticatedAdminPayoutsRouteImport } from './routes/_authenticated/admin/payouts'
import { Route as AuthenticatedAdminKycRouteImport } from './routes/_authenticated/admin/kyc'
import { Route as AuthenticatedAdminInvestorsRouteImport } from './routes/_authenticated/admin/investors'
import { Route as AuthenticatedFarmsIdIndexRouteImport } from './routes/_authenticated/farms/$id/index'
import { Route as AuthenticatedAdminFarmsIndexRouteImport } from './routes/_authenticated/admin/farms/index'
import { Route as AuthenticatedFarmsIdInvestRouteImport } from './routes/_authenticated/farms/$id/invest'
import { Route as AuthenticatedAdminUsersIdRouteImport } from './routes/_authenticated/admin/users/$id'
import { Route as AuthenticatedAdminFarmsNewRouteImport } from './routes/_authenticated/admin/farms/new'
import { Route as AuthenticatedAdminFarmsIdEditRouteImport } from './routes/_authenticated/admin/farms/$id/edit'
import { Route as AuthenticatedAdminFarmsIdAnalyticsRouteImport } from './routes/_authenticated/admin/farms/$id/analytics'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedNewsRoute = AuthenticatedNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthSignUpIndexRoute = AuthSignUpIndexRouteImport.update({
  id: '/sign-up/',
  path: '/sign-up/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInIndexRoute = AuthSignInIndexRouteImport.update({
  id: '/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordIndexRoute = AuthResetPasswordIndexRouteImport.update({
  id: '/reset-password/',
  path: '/reset-password/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordIndexRoute = AuthForgotPasswordIndexRouteImport.update({
  id: '/forgot-password/',
  path: '/forgot-password/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedWalletIndexRoute =
  AuthenticatedWalletIndexRouteImport.update({
    id: '/wallet/',
    path: '/wallet/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTransactionsIndexRoute =
  AuthenticatedTransactionsIndexRouteImport.update({
    id: '/transactions/',
    path: '/transactions/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedNotificationsIndexRoute =
  AuthenticatedNotificationsIndexRouteImport.update({
    id: '/notifications/',
    path: '/notifications/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInvestmentsIndexRoute =
  AuthenticatedInvestmentsIndexRouteImport.update({
    id: '/investments/',
    path: '/investments/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFarmsIndexRoute = AuthenticatedFarmsIndexRouteImport.update({
  id: '/farms/',
  path: '/farms/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedSettingsVerificationRoute =
  AuthenticatedSettingsVerificationRouteImport.update({
    id: '/verification',
    path: '/verification',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsSecurityRoute =
  AuthenticatedSettingsSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedPaymentCallbackRoute =
  AuthenticatedPaymentCallbackRouteImport.update({
    id: '/payment/callback',
    path: '/payment/callback',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInvestmentsIdRoute =
  AuthenticatedInvestmentsIdRouteImport.update({
    id: '/investments/$id',
    path: '/investments/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFarmIdRoute = AuthenticatedFarmIdRouteImport.update({
  id: '/farm/$id',
  path: '/farm/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminTransactionsRoute =
  AuthenticatedAdminTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminReportsRoute =
  AuthenticatedAdminReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPayoutsRoute =
  AuthenticatedAdminPayoutsRouteImport.update({
    id: '/payouts',
    path: '/payouts',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminKycRoute = AuthenticatedAdminKycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminInvestorsRoute =
  AuthenticatedAdminInvestorsRouteImport.update({
    id: '/investors',
    path: '/investors',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedFarmsIdIndexRoute =
  AuthenticatedFarmsIdIndexRouteImport.update({
    id: '/farms/$id/',
    path: '/farms/$id/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminFarmsIndexRoute =
  AuthenticatedAdminFarmsIndexRouteImport.update({
    id: '/farms/',
    path: '/farms/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedFarmsIdInvestRoute =
  AuthenticatedFarmsIdInvestRouteImport.update({
    id: '/farms/$id/invest',
    path: '/farms/$id/invest',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsersIdRoute =
  AuthenticatedAdminUsersIdRouteImport.update({
    id: '/users/$id',
    path: '/users/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFarmsNewRoute =
  AuthenticatedAdminFarmsNewRouteImport.update({
    id: '/farms/new',
    path: '/farms/new',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFarmsIdEditRoute =
  AuthenticatedAdminFarmsIdEditRouteImport.update({
    id: '/farms/$id/edit',
    path: '/farms/$id/edit',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFarmsIdAnalyticsRoute =
  AuthenticatedAdminFarmsIdAnalyticsRouteImport.update({
    id: '/farms/$id/analytics',
    path: '/farms/$id/analytics',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/news': typeof AuthenticatedNewsRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/auth/': typeof AuthIndexRoute
  '/admin/investors': typeof AuthenticatedAdminInvestorsRoute
  '/admin/kyc': typeof AuthenticatedAdminKycRoute
  '/admin/payouts': typeof AuthenticatedAdminPayoutsRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/transactions': typeof AuthenticatedAdminTransactionsRoute
  '/farm/$id': typeof AuthenticatedFarmIdRoute
  '/investments/$id': typeof AuthenticatedInvestmentsIdRoute
  '/payment/callback': typeof AuthenticatedPaymentCallbackRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/settings/security': typeof AuthenticatedSettingsSecurityRoute
  '/settings/verification': typeof AuthenticatedSettingsVerificationRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/farms/': typeof AuthenticatedFarmsIndexRoute
  '/investments/': typeof AuthenticatedInvestmentsIndexRoute
  '/notifications/': typeof AuthenticatedNotificationsIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/transactions/': typeof AuthenticatedTransactionsIndexRoute
  '/wallet/': typeof AuthenticatedWalletIndexRoute
  '/auth/forgot-password/': typeof AuthForgotPasswordIndexRoute
  '/auth/reset-password/': typeof AuthResetPasswordIndexRoute
  '/auth/sign-in/': typeof AuthSignInIndexRoute
  '/auth/sign-up/': typeof AuthSignUpIndexRoute
  '/admin/farms/new': typeof AuthenticatedAdminFarmsNewRoute
  '/admin/users/$id': typeof AuthenticatedAdminUsersIdRoute
  '/farms/$id/invest': typeof AuthenticatedFarmsIdInvestRoute
  '/admin/farms/': typeof AuthenticatedAdminFarmsIndexRoute
  '/farms/$id/': typeof AuthenticatedFarmsIdIndexRoute
  '/admin/farms/$id/analytics': typeof AuthenticatedAdminFarmsIdAnalyticsRoute
  '/admin/farms/$id/edit': typeof AuthenticatedAdminFarmsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/news': typeof AuthenticatedNewsRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/auth': typeof AuthIndexRoute
  '/admin/investors': typeof AuthenticatedAdminInvestorsRoute
  '/admin/kyc': typeof AuthenticatedAdminKycRoute
  '/admin/payouts': typeof AuthenticatedAdminPayoutsRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/transactions': typeof AuthenticatedAdminTransactionsRoute
  '/farm/$id': typeof AuthenticatedFarmIdRoute
  '/investments/$id': typeof AuthenticatedInvestmentsIdRoute
  '/payment/callback': typeof AuthenticatedPaymentCallbackRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/settings/security': typeof AuthenticatedSettingsSecurityRoute
  '/settings/verification': typeof AuthenticatedSettingsVerificationRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/farms': typeof AuthenticatedFarmsIndexRoute
  '/investments': typeof AuthenticatedInvestmentsIndexRoute
  '/notifications': typeof AuthenticatedNotificationsIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/transactions': typeof AuthenticatedTransactionsIndexRoute
  '/wallet': typeof AuthenticatedWalletIndexRoute
  '/auth/forgot-password': typeof AuthForgotPasswordIndexRoute
  '/auth/reset-password': typeof AuthResetPasswordIndexRoute
  '/auth/sign-in': typeof AuthSignInIndexRoute
  '/auth/sign-up': typeof AuthSignUpIndexRoute
  '/admin/farms/new': typeof AuthenticatedAdminFarmsNewRoute
  '/admin/users/$id': typeof AuthenticatedAdminUsersIdRoute
  '/farms/$id/invest': typeof AuthenticatedFarmsIdInvestRoute
  '/admin/farms': typeof AuthenticatedAdminFarmsIndexRoute
  '/farms/$id': typeof AuthenticatedFarmsIdIndexRoute
  '/admin/farms/$id/analytics': typeof AuthenticatedAdminFarmsIdAnalyticsRoute
  '/admin/farms/$id/edit': typeof AuthenticatedAdminFarmsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/news': typeof AuthenticatedNewsRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/auth/': typeof AuthIndexRoute
  '/_authenticated/admin/investors': typeof AuthenticatedAdminInvestorsRoute
  '/_authenticated/admin/kyc': typeof AuthenticatedAdminKycRoute
  '/_authenticated/admin/payouts': typeof AuthenticatedAdminPayoutsRoute
  '/_authenticated/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/_authenticated/admin/transactions': typeof AuthenticatedAdminTransactionsRoute
  '/_authenticated/farm/$id': typeof AuthenticatedFarmIdRoute
  '/_authenticated/investments/$id': typeof AuthenticatedInvestmentsIdRoute
  '/_authenticated/payment/callback': typeof AuthenticatedPaymentCallbackRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/settings/security': typeof AuthenticatedSettingsSecurityRoute
  '/_authenticated/settings/verification': typeof AuthenticatedSettingsVerificationRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/farms/': typeof AuthenticatedFarmsIndexRoute
  '/_authenticated/investments/': typeof AuthenticatedInvestmentsIndexRoute
  '/_authenticated/notifications/': typeof AuthenticatedNotificationsIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/transactions/': typeof AuthenticatedTransactionsIndexRoute
  '/_authenticated/wallet/': typeof AuthenticatedWalletIndexRoute
  '/auth/forgot-password/': typeof AuthForgotPasswordIndexRoute
  '/auth/reset-password/': typeof AuthResetPasswordIndexRoute
  '/auth/sign-in/': typeof AuthSignInIndexRoute
  '/auth/sign-up/': typeof AuthSignUpIndexRoute
  '/_authenticated/admin/farms/new': typeof AuthenticatedAdminFarmsNewRoute
  '/_authenticated/admin/users/$id': typeof AuthenticatedAdminUsersIdRoute
  '/_authenticated/farms/$id/invest': typeof AuthenticatedFarmsIdInvestRoute
  '/_authenticated/admin/farms/': typeof AuthenticatedAdminFarmsIndexRoute
  '/_authenticated/farms/$id/': typeof AuthenticatedFarmsIdIndexRoute
  '/_authenticated/admin/farms/$id/analytics': typeof AuthenticatedAdminFarmsIdAnalyticsRoute
  '/_authenticated/admin/farms/$id/edit': typeof AuthenticatedAdminFarmsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/privacy'
    | '/support'
    | '/terms'
    | '/settings'
    | '/admin'
    | '/news'
    | '/auth/verify-email'
    | '/auth/'
    | '/admin/investors'
    | '/admin/kyc'
    | '/admin/payouts'
    | '/admin/reports'
    | '/admin/transactions'
    | '/farm/$id'
    | '/investments/$id'
    | '/payment/callback'
    | '/settings/notifications'
    | '/settings/security'
    | '/settings/verification'
    | '/admin/'
    | '/dashboard/'
    | '/farms/'
    | '/investments/'
    | '/notifications/'
    | '/settings/'
    | '/transactions/'
    | '/wallet/'
    | '/auth/forgot-password/'
    | '/auth/reset-password/'
    | '/auth/sign-in/'
    | '/auth/sign-up/'
    | '/admin/farms/new'
    | '/admin/users/$id'
    | '/farms/$id/invest'
    | '/admin/farms/'
    | '/farms/$id/'
    | '/admin/farms/$id/analytics'
    | '/admin/farms/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/privacy'
    | '/support'
    | '/terms'
    | '/news'
    | '/auth/verify-email'
    | '/auth'
    | '/admin/investors'
    | '/admin/kyc'
    | '/admin/payouts'
    | '/admin/reports'
    | '/admin/transactions'
    | '/farm/$id'
    | '/investments/$id'
    | '/payment/callback'
    | '/settings/notifications'
    | '/settings/security'
    | '/settings/verification'
    | '/admin'
    | '/dashboard'
    | '/farms'
    | '/investments'
    | '/notifications'
    | '/settings'
    | '/transactions'
    | '/wallet'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/admin/farms/new'
    | '/admin/users/$id'
    | '/farms/$id/invest'
    | '/admin/farms'
    | '/farms/$id'
    | '/admin/farms/$id/analytics'
    | '/admin/farms/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/onboarding'
    | '/privacy'
    | '/support'
    | '/terms'
    | '/_authenticated/settings'
    | '/_authenticated/admin'
    | '/_authenticated/news'
    | '/auth/verify-email'
    | '/auth/'
    | '/_authenticated/admin/investors'
    | '/_authenticated/admin/kyc'
    | '/_authenticated/admin/payouts'
    | '/_authenticated/admin/reports'
    | '/_authenticated/admin/transactions'
    | '/_authenticated/farm/$id'
    | '/_authenticated/investments/$id'
    | '/_authenticated/payment/callback'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/settings/security'
    | '/_authenticated/settings/verification'
    | '/_authenticated/admin/'
    | '/_authenticated/dashboard/'
    | '/_authenticated/farms/'
    | '/_authenticated/investments/'
    | '/_authenticated/notifications/'
    | '/_authenticated/settings/'
    | '/_authenticated/transactions/'
    | '/_authenticated/wallet/'
    | '/auth/forgot-password/'
    | '/auth/reset-password/'
    | '/auth/sign-in/'
    | '/auth/sign-up/'
    | '/_authenticated/admin/farms/new'
    | '/_authenticated/admin/users/$id'
    | '/_authenticated/farms/$id/invest'
    | '/_authenticated/admin/farms/'
    | '/_authenticated/farms/$id/'
    | '/_authenticated/admin/farms/$id/analytics'
    | '/_authenticated/admin/farms/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  PrivacyRoute: typeof PrivacyRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/verify-email': {
      id: '/auth/verify-email'
      path: '/verify-email'
      fullPath: '/auth/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/news': {
      id: '/_authenticated/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof AuthenticatedNewsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/sign-up/': {
      id: '/auth/sign-up/'
      path: '/sign-up'
      fullPath: '/auth/sign-up/'
      preLoaderRoute: typeof AuthSignUpIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/sign-in/': {
      id: '/auth/sign-in/'
      path: '/sign-in'
      fullPath: '/auth/sign-in/'
      preLoaderRoute: typeof AuthSignInIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/reset-password/': {
      id: '/auth/reset-password/'
      path: '/reset-password'
      fullPath: '/auth/reset-password/'
      preLoaderRoute: typeof AuthResetPasswordIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot-password/': {
      id: '/auth/forgot-password/'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password/'
      preLoaderRoute: typeof AuthForgotPasswordIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/wallet/': {
      id: '/_authenticated/wallet/'
      path: '/wallet'
      fullPath: '/wallet/'
      preLoaderRoute: typeof AuthenticatedWalletIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transactions/': {
      id: '/_authenticated/transactions/'
      path: '/transactions'
      fullPath: '/transactions/'
      preLoaderRoute: typeof AuthenticatedTransactionsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/notifications/': {
      id: '/_authenticated/notifications/'
      path: '/notifications'
      fullPath: '/notifications/'
      preLoaderRoute: typeof AuthenticatedNotificationsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/investments/': {
      id: '/_authenticated/investments/'
      path: '/investments'
      fullPath: '/investments/'
      preLoaderRoute: typeof AuthenticatedInvestmentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/farms/': {
      id: '/_authenticated/farms/'
      path: '/farms'
      fullPath: '/farms/'
      preLoaderRoute: typeof AuthenticatedFarmsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/settings/verification': {
      id: '/_authenticated/settings/verification'
      path: '/verification'
      fullPath: '/settings/verification'
      preLoaderRoute: typeof AuthenticatedSettingsVerificationRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/security': {
      id: '/_authenticated/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof AuthenticatedSettingsSecurityRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/payment/callback': {
      id: '/_authenticated/payment/callback'
      path: '/payment/callback'
      fullPath: '/payment/callback'
      preLoaderRoute: typeof AuthenticatedPaymentCallbackRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/investments/$id': {
      id: '/_authenticated/investments/$id'
      path: '/investments/$id'
      fullPath: '/investments/$id'
      preLoaderRoute: typeof AuthenticatedInvestmentsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/farm/$id': {
      id: '/_authenticated/farm/$id'
      path: '/farm/$id'
      fullPath: '/farm/$id'
      preLoaderRoute: typeof AuthenticatedFarmIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/transactions': {
      id: '/_authenticated/admin/transactions'
      path: '/transactions'
      fullPath: '/admin/transactions'
      preLoaderRoute: typeof AuthenticatedAdminTransactionsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/reports': {
      id: '/_authenticated/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AuthenticatedAdminReportsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/payouts': {
      id: '/_authenticated/admin/payouts'
      path: '/payouts'
      fullPath: '/admin/payouts'
      preLoaderRoute: typeof AuthenticatedAdminPayoutsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/kyc': {
      id: '/_authenticated/admin/kyc'
      path: '/kyc'
      fullPath: '/admin/kyc'
      preLoaderRoute: typeof AuthenticatedAdminKycRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/investors': {
      id: '/_authenticated/admin/investors'
      path: '/investors'
      fullPath: '/admin/investors'
      preLoaderRoute: typeof AuthenticatedAdminInvestorsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/farms/$id/': {
      id: '/_authenticated/farms/$id/'
      path: '/farms/$id'
      fullPath: '/farms/$id/'
      preLoaderRoute: typeof AuthenticatedFarmsIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/farms/': {
      id: '/_authenticated/admin/farms/'
      path: '/farms'
      fullPath: '/admin/farms/'
      preLoaderRoute: typeof AuthenticatedAdminFarmsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/farms/$id/invest': {
      id: '/_authenticated/farms/$id/invest'
      path: '/farms/$id/invest'
      fullPath: '/farms/$id/invest'
      preLoaderRoute: typeof AuthenticatedFarmsIdInvestRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users/$id': {
      id: '/_authenticated/admin/users/$id'
      path: '/users/$id'
      fullPath: '/admin/users/$id'
      preLoaderRoute: typeof AuthenticatedAdminUsersIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/farms/new': {
      id: '/_authenticated/admin/farms/new'
      path: '/farms/new'
      fullPath: '/admin/farms/new'
      preLoaderRoute: typeof AuthenticatedAdminFarmsNewRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/farms/$id/edit': {
      id: '/_authenticated/admin/farms/$id/edit'
      path: '/farms/$id/edit'
      fullPath: '/admin/farms/$id/edit'
      preLoaderRoute: typeof AuthenticatedAdminFarmsIdEditRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/farms/$id/analytics': {
      id: '/_authenticated/admin/farms/$id/analytics'
      path: '/farms/$id/analytics'
      fullPath: '/admin/farms/$id/analytics'
      preLoaderRoute: typeof AuthenticatedAdminFarmsIdAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsSecurityRoute: typeof AuthenticatedSettingsSecurityRoute
  AuthenticatedSettingsVerificationRoute: typeof AuthenticatedSettingsVerificationRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsSecurityRoute: AuthenticatedSettingsSecurityRoute,
    AuthenticatedSettingsVerificationRoute:
      AuthenticatedSettingsVerificationRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminInvestorsRoute: typeof AuthenticatedAdminInvestorsRoute
  AuthenticatedAdminKycRoute: typeof AuthenticatedAdminKycRoute
  AuthenticatedAdminPayoutsRoute: typeof AuthenticatedAdminPayoutsRoute
  AuthenticatedAdminReportsRoute: typeof AuthenticatedAdminReportsRoute
  AuthenticatedAdminTransactionsRoute: typeof AuthenticatedAdminTransactionsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminFarmsNewRoute: typeof AuthenticatedAdminFarmsNewRoute
  AuthenticatedAdminUsersIdRoute: typeof AuthenticatedAdminUsersIdRoute
  AuthenticatedAdminFarmsIndexRoute: typeof AuthenticatedAdminFarmsIndexRoute
  AuthenticatedAdminFarmsIdAnalyticsRoute: typeof AuthenticatedAdminFarmsIdAnalyticsRoute
  AuthenticatedAdminFarmsIdEditRoute: typeof AuthenticatedAdminFarmsIdEditRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminInvestorsRoute: AuthenticatedAdminInvestorsRoute,
  AuthenticatedAdminKycRoute: AuthenticatedAdminKycRoute,
  AuthenticatedAdminPayoutsRoute: AuthenticatedAdminPayoutsRoute,
  AuthenticatedAdminReportsRoute: AuthenticatedAdminReportsRoute,
  AuthenticatedAdminTransactionsRoute: AuthenticatedAdminTransactionsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminFarmsNewRoute: AuthenticatedAdminFarmsNewRoute,
  AuthenticatedAdminUsersIdRoute: AuthenticatedAdminUsersIdRoute,
  AuthenticatedAdminFarmsIndexRoute: AuthenticatedAdminFarmsIndexRoute,
  AuthenticatedAdminFarmsIdAnalyticsRoute:
    AuthenticatedAdminFarmsIdAnalyticsRoute,
  AuthenticatedAdminFarmsIdEditRoute: AuthenticatedAdminFarmsIdEditRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedNewsRoute: typeof AuthenticatedNewsRoute
  AuthenticatedFarmIdRoute: typeof AuthenticatedFarmIdRoute
  AuthenticatedInvestmentsIdRoute: typeof AuthenticatedInvestmentsIdRoute
  AuthenticatedPaymentCallbackRoute: typeof AuthenticatedPaymentCallbackRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedFarmsIndexRoute: typeof AuthenticatedFarmsIndexRoute
  AuthenticatedInvestmentsIndexRoute: typeof AuthenticatedInvestmentsIndexRoute
  AuthenticatedNotificationsIndexRoute: typeof AuthenticatedNotificationsIndexRoute
  AuthenticatedTransactionsIndexRoute: typeof AuthenticatedTransactionsIndexRoute
  AuthenticatedWalletIndexRoute: typeof AuthenticatedWalletIndexRoute
  AuthenticatedFarmsIdInvestRoute: typeof AuthenticatedFarmsIdInvestRoute
  AuthenticatedFarmsIdIndexRoute: typeof AuthenticatedFarmsIdIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedNewsRoute: AuthenticatedNewsRoute,
  AuthenticatedFarmIdRoute: AuthenticatedFarmIdRoute,
  AuthenticatedInvestmentsIdRoute: AuthenticatedInvestmentsIdRoute,
  AuthenticatedPaymentCallbackRoute: AuthenticatedPaymentCallbackRoute,
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  AuthenticatedFarmsIndexRoute: AuthenticatedFarmsIndexRoute,
  AuthenticatedInvestmentsIndexRoute: AuthenticatedInvestmentsIndexRoute,
  AuthenticatedNotificationsIndexRoute: AuthenticatedNotificationsIndexRoute,
  AuthenticatedTransactionsIndexRoute: AuthenticatedTransactionsIndexRoute,
  AuthenticatedWalletIndexRoute: AuthenticatedWalletIndexRoute,
  AuthenticatedFarmsIdInvestRoute: AuthenticatedFarmsIdInvestRoute,
  AuthenticatedFarmsIdIndexRoute: AuthenticatedFarmsIdIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
  AuthIndexRoute: typeof AuthIndexRoute
  AuthForgotPasswordIndexRoute: typeof AuthForgotPasswordIndexRoute
  AuthResetPasswordIndexRoute: typeof AuthResetPasswordIndexRoute
  AuthSignInIndexRoute: typeof AuthSignInIndexRoute
  AuthSignUpIndexRoute: typeof AuthSignUpIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
  AuthIndexRoute: AuthIndexRoute,
  AuthForgotPasswordIndexRoute: AuthForgotPasswordIndexRoute,
  AuthResetPasswordIndexRoute: AuthResetPasswordIndexRoute,
  AuthSignInIndexRoute: AuthSignInIndexRoute,
  AuthSignUpIndexRoute: AuthSignUpIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  PrivacyRoute: PrivacyRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
