/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as NewsRouteImport } from './routes/news'
import { Route as MyInvestmentsRouteImport } from './routes/my-investments'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthIndexRouteImport } from './routes/auth.index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as PaymentCallbackRouteImport } from './routes/payment.callback'
import { Route as FarmIdRouteImport } from './routes/farm.$id'
import { Route as AuthSignUpRouteImport } from './routes/auth.sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth.sign-in'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth.forgot-password'
import { Route as AdminTransactionsRouteImport } from './routes/admin/transactions'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminInvestorsRouteImport } from './routes/admin/investors'
import { Route as AdminFarmsRouteImport } from './routes/admin/farms'
import { Route as AdminFarmNewRouteImport } from './routes/admin/farm.new'

const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const MyInvestmentsRoute = MyInvestmentsRouteImport.update({
  id: '/my-investments',
  path: '/my-investments',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentCallbackRoute = PaymentCallbackRouteImport.update({
  id: '/payment/callback',
  path: '/payment/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmIdRoute = FarmIdRouteImport.update({
  id: '/farm/$id',
  path: '/farm/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AdminTransactionsRoute = AdminTransactionsRouteImport.update({
  id: '/admin/transactions',
  path: '/admin/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInvestorsRoute = AdminInvestorsRouteImport.update({
  id: '/admin/investors',
  path: '/admin/investors',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFarmsRoute = AdminFarmsRouteImport.update({
  id: '/admin/farms',
  path: '/admin/farms',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFarmNewRoute = AdminFarmNewRouteImport.update({
  id: '/admin/farm/new',
  path: '/admin/farm/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/discover': typeof DiscoverRoute
  '/my-investments': typeof MyInvestmentsRoute
  '/news': typeof NewsRoute
  '/transactions': typeof TransactionsRoute
  '/admin/farms': typeof AdminFarmsRoute
  '/admin/investors': typeof AdminInvestorsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/farm/$id': typeof FarmIdRoute
  '/payment/callback': typeof PaymentCallbackRoute
  '/admin': typeof AdminIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/admin/farm/new': typeof AdminFarmNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/discover': typeof DiscoverRoute
  '/my-investments': typeof MyInvestmentsRoute
  '/news': typeof NewsRoute
  '/transactions': typeof TransactionsRoute
  '/admin/farms': typeof AdminFarmsRoute
  '/admin/investors': typeof AdminInvestorsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/farm/$id': typeof FarmIdRoute
  '/payment/callback': typeof PaymentCallbackRoute
  '/admin': typeof AdminIndexRoute
  '/auth': typeof AuthIndexRoute
  '/admin/farm/new': typeof AdminFarmNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/discover': typeof DiscoverRoute
  '/my-investments': typeof MyInvestmentsRoute
  '/news': typeof NewsRoute
  '/transactions': typeof TransactionsRoute
  '/admin/farms': typeof AdminFarmsRoute
  '/admin/investors': typeof AdminInvestorsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/farm/$id': typeof FarmIdRoute
  '/payment/callback': typeof PaymentCallbackRoute
  '/admin/': typeof AdminIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/admin/farm/new': typeof AdminFarmNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/discover'
    | '/my-investments'
    | '/news'
    | '/transactions'
    | '/admin/farms'
    | '/admin/investors'
    | '/admin/reports'
    | '/admin/transactions'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/farm/$id'
    | '/payment/callback'
    | '/admin'
    | '/auth/'
    | '/admin/farm/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/discover'
    | '/my-investments'
    | '/news'
    | '/transactions'
    | '/admin/farms'
    | '/admin/investors'
    | '/admin/reports'
    | '/admin/transactions'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/farm/$id'
    | '/payment/callback'
    | '/admin'
    | '/auth'
    | '/admin/farm/new'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/discover'
    | '/my-investments'
    | '/news'
    | '/transactions'
    | '/admin/farms'
    | '/admin/investors'
    | '/admin/reports'
    | '/admin/transactions'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/farm/$id'
    | '/payment/callback'
    | '/admin/'
    | '/auth/'
    | '/admin/farm/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  DiscoverRoute: typeof DiscoverRoute
  MyInvestmentsRoute: typeof MyInvestmentsRoute
  NewsRoute: typeof NewsRoute
  TransactionsRoute: typeof TransactionsRoute
  AdminFarmsRoute: typeof AdminFarmsRoute
  AdminInvestorsRoute: typeof AdminInvestorsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminTransactionsRoute: typeof AdminTransactionsRoute
  FarmIdRoute: typeof FarmIdRoute
  PaymentCallbackRoute: typeof PaymentCallbackRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminFarmNewRoute: typeof AdminFarmNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-investments': {
      id: '/my-investments'
      path: '/my-investments'
      fullPath: '/my-investments'
      preLoaderRoute: typeof MyInvestmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/callback': {
      id: '/payment/callback'
      path: '/payment/callback'
      fullPath: '/payment/callback'
      preLoaderRoute: typeof PaymentCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farm/$id': {
      id: '/farm/$id'
      path: '/farm/$id'
      fullPath: '/farm/$id'
      preLoaderRoute: typeof FarmIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/admin/transactions': {
      id: '/admin/transactions'
      path: '/admin/transactions'
      fullPath: '/admin/transactions'
      preLoaderRoute: typeof AdminTransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/investors': {
      id: '/admin/investors'
      path: '/admin/investors'
      fullPath: '/admin/investors'
      preLoaderRoute: typeof AdminInvestorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/farms': {
      id: '/admin/farms'
      path: '/admin/farms'
      fullPath: '/admin/farms'
      preLoaderRoute: typeof AdminFarmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/farm/new': {
      id: '/admin/farm/new'
      path: '/admin/farm/new'
      fullPath: '/admin/farm/new'
      preLoaderRoute: typeof AdminFarmNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  DashboardRoute: DashboardRoute,
  DiscoverRoute: DiscoverRoute,
  MyInvestmentsRoute: MyInvestmentsRoute,
  NewsRoute: NewsRoute,
  TransactionsRoute: TransactionsRoute,
  AdminFarmsRoute: AdminFarmsRoute,
  AdminInvestorsRoute: AdminInvestorsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminTransactionsRoute: AdminTransactionsRoute,
  FarmIdRoute: FarmIdRoute,
  PaymentCallbackRoute: PaymentCallbackRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminFarmNewRoute: AdminFarmNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
