/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as SuperAdminRouteRouteImport } from './routes/super-admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuperAdminIndexRouteImport } from './routes/super-admin/index'
import { Route as TenantIndexRouteImport } from './routes/$tenant/index'
import { Route as SuperAdminTenantsRouteImport } from './routes/super-admin/tenants'
import { Route as SuperAdminReadinessRouteImport } from './routes/super-admin/readiness'
import { Route as SuperAdminAccessRouteImport } from './routes/super-admin/access'
import { Route as TenantTermsRouteImport } from './routes/$tenant/terms'
import { Route as TenantSupportRouteImport } from './routes/$tenant/support'
import { Route as TenantPrivacyRouteImport } from './routes/$tenant/privacy'
import { Route as TenantOnboardingRouteImport } from './routes/$tenant/onboarding'
import { Route as TenantAuthRouteRouteImport } from './routes/$tenant/auth/route'
import { Route as TenantAuthenticatedRouteRouteImport } from './routes/$tenant/_authenticated/route'
import { Route as TenantAuthIndexRouteImport } from './routes/$tenant/auth/index'
import { Route as TenantAuthVerifyEmailRouteImport } from './routes/$tenant/auth/verify-email'
import { Route as TenantAuthenticatedNewsRouteImport } from './routes/$tenant/_authenticated/news'
import { Route as TenantAuthenticatedAdminRouteImport } from './routes/$tenant/_authenticated/admin'
import { Route as TenantAuthenticatedSettingsRouteRouteImport } from './routes/$tenant/_authenticated/settings/route'
import { Route as TenantAuthSignUpIndexRouteImport } from './routes/$tenant/auth/sign-up/index'
import { Route as TenantAuthSignInIndexRouteImport } from './routes/$tenant/auth/sign-in/index'
import { Route as TenantAuthResetPasswordIndexRouteImport } from './routes/$tenant/auth/reset-password/index'
import { Route as TenantAuthForgotPasswordIndexRouteImport } from './routes/$tenant/auth/forgot-password/index'
import { Route as TenantAuthenticatedWalletIndexRouteImport } from './routes/$tenant/_authenticated/wallet/index'
import { Route as TenantAuthenticatedTransactionsIndexRouteImport } from './routes/$tenant/_authenticated/transactions/index'
import { Route as TenantAuthenticatedSettingsIndexRouteImport } from './routes/$tenant/_authenticated/settings/index'
import { Route as TenantAuthenticatedNotificationsIndexRouteImport } from './routes/$tenant/_authenticated/notifications/index'
import { Route as TenantAuthenticatedInvestmentsIndexRouteImport } from './routes/$tenant/_authenticated/investments/index'
import { Route as TenantAuthenticatedFarmsIndexRouteImport } from './routes/$tenant/_authenticated/farms/index'
import { Route as TenantAuthenticatedDashboardIndexRouteImport } from './routes/$tenant/_authenticated/dashboard/index'
import { Route as TenantAuthenticatedAdminIndexRouteImport } from './routes/$tenant/_authenticated/admin/index'
import { Route as TenantAuthenticatedSettingsVerificationRouteImport } from './routes/$tenant/_authenticated/settings/verification'
import { Route as TenantAuthenticatedSettingsSecurityRouteImport } from './routes/$tenant/_authenticated/settings/security'
import { Route as TenantAuthenticatedSettingsNotificationsRouteImport } from './routes/$tenant/_authenticated/settings/notifications'
import { Route as TenantAuthenticatedPaymentCallbackRouteImport } from './routes/$tenant/_authenticated/payment/callback'
import { Route as TenantAuthenticatedInvestmentsIdRouteImport } from './routes/$tenant/_authenticated/investments/$id'
import { Route as TenantAuthenticatedFarmIdRouteImport } from './routes/$tenant/_authenticated/farm/$id'
import { Route as TenantAuthenticatedAdminTransactionsRouteImport } from './routes/$tenant/_authenticated/admin/transactions'
import { Route as TenantAuthenticatedAdminReportsRouteImport } from './routes/$tenant/_authenticated/admin/reports'
import { Route as TenantAuthenticatedAdminPayoutsRouteImport } from './routes/$tenant/_authenticated/admin/payouts'
import { Route as TenantAuthenticatedAdminKycRouteImport } from './routes/$tenant/_authenticated/admin/kyc'
import { Route as TenantAuthenticatedAdminInvestorsRouteImport } from './routes/$tenant/_authenticated/admin/investors'
import { Route as TenantAuthenticatedFarmsIdIndexRouteImport } from './routes/$tenant/_authenticated/farms/$id/index'
import { Route as TenantAuthenticatedAdminFarmsIndexRouteImport } from './routes/$tenant/_authenticated/admin/farms/index'
import { Route as TenantAuthenticatedFarmsIdInvestRouteImport } from './routes/$tenant/_authenticated/farms/$id/invest'
import { Route as TenantAuthenticatedAdminUsersIdRouteImport } from './routes/$tenant/_authenticated/admin/users/$id'
import { Route as TenantAuthenticatedAdminFarmsNewRouteImport } from './routes/$tenant/_authenticated/admin/farms/new'
import { Route as TenantAuthenticatedAdminFarmsIdEditRouteImport } from './routes/$tenant/_authenticated/admin/farms/$id/edit'
import { Route as TenantAuthenticatedAdminFarmsIdAnalyticsRouteImport } from './routes/$tenant/_authenticated/admin/farms/$id/analytics'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminRouteRoute = SuperAdminRouteRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminIndexRoute = SuperAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SuperAdminRouteRoute,
} as any)
const TenantIndexRoute = TenantIndexRouteImport.update({
  id: '/$tenant/',
  path: '/$tenant/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminTenantsRoute = SuperAdminTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => SuperAdminRouteRoute,
} as any)
const SuperAdminReadinessRoute = SuperAdminReadinessRouteImport.update({
  id: '/readiness',
  path: '/readiness',
  getParentRoute: () => SuperAdminRouteRoute,
} as any)
const SuperAdminAccessRoute = SuperAdminAccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => SuperAdminRouteRoute,
} as any)
const TenantTermsRoute = TenantTermsRouteImport.update({
  id: '/$tenant/terms',
  path: '/$tenant/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantSupportRoute = TenantSupportRouteImport.update({
  id: '/$tenant/support',
  path: '/$tenant/support',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantPrivacyRoute = TenantPrivacyRouteImport.update({
  id: '/$tenant/privacy',
  path: '/$tenant/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantOnboardingRoute = TenantOnboardingRouteImport.update({
  id: '/$tenant/onboarding',
  path: '/$tenant/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantAuthRouteRoute = TenantAuthRouteRouteImport.update({
  id: '/$tenant/auth',
  path: '/$tenant/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantAuthenticatedRouteRoute =
  TenantAuthenticatedRouteRouteImport.update({
    id: '/$tenant/_authenticated',
    path: '/$tenant',
    getParentRoute: () => rootRouteImport,
  } as any)
const TenantAuthIndexRoute = TenantAuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TenantAuthRouteRoute,
} as any)
const TenantAuthVerifyEmailRoute = TenantAuthVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => TenantAuthRouteRoute,
} as any)
const TenantAuthenticatedNewsRoute = TenantAuthenticatedNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => TenantAuthenticatedRouteRoute,
} as any)
const TenantAuthenticatedAdminRoute =
  TenantAuthenticatedAdminRouteImport.update({
    id: '/admin',
    path: '/admin',
    getParentRoute: () => TenantAuthenticatedRouteRoute,
  } as any)
const TenantAuthenticatedSettingsRouteRoute =
  TenantAuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => TenantAuthenticatedRouteRoute,
  } as any)
const TenantAuthSignUpIndexRoute = TenantAuthSignUpIndexRouteImport.update({
  id: '/sign-up/',
  path: '/sign-up/',
  getParentRoute: () => TenantAuthRouteRoute,
} as any)
const TenantAuthSignInIndexRoute = TenantAuthSignInIndexRouteImport.update({
  id: '/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => TenantAuthRouteRoute,
} as any)
const TenantAuthResetPasswordIndexRoute =
  TenantAuthResetPasswordIndexRouteImport.update({
    id: '/reset-password/',
    path: '/reset-password/',
    getParentRoute: () => TenantAuthRouteRoute,
  } as any)
const TenantAuthForgotPasswordIndexRoute =
  TenantAuthForgotPasswordIndexRouteImport.update({
    id: '/forgot-password/',
    path: '/forgot-password/',
    getParentRoute: () => TenantAuthRouteRoute,
  } as any)
const TenantAuthenticatedWalletIndexRoute =
  TenantAuthenticatedWalletIndexRouteImport.update({
    id: '/wallet/',
    path: '/wallet/',
    getParentRoute: () => TenantAuthenticatedRouteRoute,
  } as any)
const TenantAuthenticatedTransactionsIndexRoute =
  TenantAuthenticatedTransactionsIndexRouteImport.update({
    id: '/transactions/',
    path: '/transactions/',
    getParentRoute: () => TenantAuthenticatedRouteRoute,
  } as any)
const TenantAuthenticatedSettingsIndexRoute =
  TenantAuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => TenantAuthenticatedSettingsRouteRoute,
  } as any)
const TenantAuthenticatedNotificationsIndexRoute =
  TenantAuthenticatedNotificationsIndexRouteImport.update({
    id: '/notifications/',
    path: '/notifications/',
    getParentRoute: () => TenantAuthenticatedRouteRoute,
  } as any)
const TenantAuthenticatedInvestmentsIndexRoute =
  TenantAuthenticatedInvestmentsIndexRouteImport.update({
    id: '/investments/',
    path: '/investments/',
    getParentRoute: () => TenantAuthenticatedRouteRoute,
  } as any)
const TenantAuthenticatedFarmsIndexRoute =
  TenantAuthenticatedFarmsIndexRouteImport.update({
    id: '/farms/',
    path: '/farms/',
    getParentRoute: () => TenantAuthenticatedRouteRoute,
  } as any)
const TenantAuthenticatedDashboardIndexRoute =
  TenantAuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => TenantAuthenticatedRouteRoute,
  } as any)
const TenantAuthenticatedAdminIndexRoute =
  TenantAuthenticatedAdminIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => TenantAuthenticatedAdminRoute,
  } as any)
const TenantAuthenticatedSettingsVerificationRoute =
  TenantAuthenticatedSettingsVerificationRouteImport.update({
    id: '/verification',
    path: '/verification',
    getParentRoute: () => TenantAuthenticatedSettingsRouteRoute,
  } as any)
const TenantAuthenticatedSettingsSecurityRoute =
  TenantAuthenticatedSettingsSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => TenantAuthenticatedSettingsRouteRoute,
  } as any)
const TenantAuthenticatedSettingsNotificationsRoute =
  TenantAuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => TenantAuthenticatedSettingsRouteRoute,
  } as any)
const TenantAuthenticatedPaymentCallbackRoute =
  TenantAuthenticatedPaymentCallbackRouteImport.update({
    id: '/payment/callback',
    path: '/payment/callback',
    getParentRoute: () => TenantAuthenticatedRouteRoute,
  } as any)
const TenantAuthenticatedInvestmentsIdRoute =
  TenantAuthenticatedInvestmentsIdRouteImport.update({
    id: '/investments/$id',
    path: '/investments/$id',
    getParentRoute: () => TenantAuthenticatedRouteRoute,
  } as any)
const TenantAuthenticatedFarmIdRoute =
  TenantAuthenticatedFarmIdRouteImport.update({
    id: '/farm/$id',
    path: '/farm/$id',
    getParentRoute: () => TenantAuthenticatedRouteRoute,
  } as any)
const TenantAuthenticatedAdminTransactionsRoute =
  TenantAuthenticatedAdminTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => TenantAuthenticatedAdminRoute,
  } as any)
const TenantAuthenticatedAdminReportsRoute =
  TenantAuthenticatedAdminReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => TenantAuthenticatedAdminRoute,
  } as any)
const TenantAuthenticatedAdminPayoutsRoute =
  TenantAuthenticatedAdminPayoutsRouteImport.update({
    id: '/payouts',
    path: '/payouts',
    getParentRoute: () => TenantAuthenticatedAdminRoute,
  } as any)
const TenantAuthenticatedAdminKycRoute =
  TenantAuthenticatedAdminKycRouteImport.update({
    id: '/kyc',
    path: '/kyc',
    getParentRoute: () => TenantAuthenticatedAdminRoute,
  } as any)
const TenantAuthenticatedAdminInvestorsRoute =
  TenantAuthenticatedAdminInvestorsRouteImport.update({
    id: '/investors',
    path: '/investors',
    getParentRoute: () => TenantAuthenticatedAdminRoute,
  } as any)
const TenantAuthenticatedFarmsIdIndexRoute =
  TenantAuthenticatedFarmsIdIndexRouteImport.update({
    id: '/farms/$id/',
    path: '/farms/$id/',
    getParentRoute: () => TenantAuthenticatedRouteRoute,
  } as any)
const TenantAuthenticatedAdminFarmsIndexRoute =
  TenantAuthenticatedAdminFarmsIndexRouteImport.update({
    id: '/farms/',
    path: '/farms/',
    getParentRoute: () => TenantAuthenticatedAdminRoute,
  } as any)
const TenantAuthenticatedFarmsIdInvestRoute =
  TenantAuthenticatedFarmsIdInvestRouteImport.update({
    id: '/farms/$id/invest',
    path: '/farms/$id/invest',
    getParentRoute: () => TenantAuthenticatedRouteRoute,
  } as any)
const TenantAuthenticatedAdminUsersIdRoute =
  TenantAuthenticatedAdminUsersIdRouteImport.update({
    id: '/users/$id',
    path: '/users/$id',
    getParentRoute: () => TenantAuthenticatedAdminRoute,
  } as any)
const TenantAuthenticatedAdminFarmsNewRoute =
  TenantAuthenticatedAdminFarmsNewRouteImport.update({
    id: '/farms/new',
    path: '/farms/new',
    getParentRoute: () => TenantAuthenticatedAdminRoute,
  } as any)
const TenantAuthenticatedAdminFarmsIdEditRoute =
  TenantAuthenticatedAdminFarmsIdEditRouteImport.update({
    id: '/farms/$id/edit',
    path: '/farms/$id/edit',
    getParentRoute: () => TenantAuthenticatedAdminRoute,
  } as any)
const TenantAuthenticatedAdminFarmsIdAnalyticsRoute =
  TenantAuthenticatedAdminFarmsIdAnalyticsRouteImport.update({
    id: '/farms/$id/analytics',
    path: '/farms/$id/analytics',
    getParentRoute: () => TenantAuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/super-admin': typeof SuperAdminRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/$tenant': typeof TenantAuthenticatedRouteRouteWithChildren
  '/$tenant/auth': typeof TenantAuthRouteRouteWithChildren
  '/$tenant/onboarding': typeof TenantOnboardingRoute
  '/$tenant/privacy': typeof TenantPrivacyRoute
  '/$tenant/support': typeof TenantSupportRoute
  '/$tenant/terms': typeof TenantTermsRoute
  '/super-admin/access': typeof SuperAdminAccessRoute
  '/super-admin/readiness': typeof SuperAdminReadinessRoute
  '/super-admin/tenants': typeof SuperAdminTenantsRoute
  '/$tenant/': typeof TenantIndexRoute
  '/super-admin/': typeof SuperAdminIndexRoute
  '/$tenant/settings': typeof TenantAuthenticatedSettingsRouteRouteWithChildren
  '/$tenant/admin': typeof TenantAuthenticatedAdminRouteWithChildren
  '/$tenant/news': typeof TenantAuthenticatedNewsRoute
  '/$tenant/auth/verify-email': typeof TenantAuthVerifyEmailRoute
  '/$tenant/auth/': typeof TenantAuthIndexRoute
  '/$tenant/admin/investors': typeof TenantAuthenticatedAdminInvestorsRoute
  '/$tenant/admin/kyc': typeof TenantAuthenticatedAdminKycRoute
  '/$tenant/admin/payouts': typeof TenantAuthenticatedAdminPayoutsRoute
  '/$tenant/admin/reports': typeof TenantAuthenticatedAdminReportsRoute
  '/$tenant/admin/transactions': typeof TenantAuthenticatedAdminTransactionsRoute
  '/$tenant/farm/$id': typeof TenantAuthenticatedFarmIdRoute
  '/$tenant/investments/$id': typeof TenantAuthenticatedInvestmentsIdRoute
  '/$tenant/payment/callback': typeof TenantAuthenticatedPaymentCallbackRoute
  '/$tenant/settings/notifications': typeof TenantAuthenticatedSettingsNotificationsRoute
  '/$tenant/settings/security': typeof TenantAuthenticatedSettingsSecurityRoute
  '/$tenant/settings/verification': typeof TenantAuthenticatedSettingsVerificationRoute
  '/$tenant/admin/': typeof TenantAuthenticatedAdminIndexRoute
  '/$tenant/dashboard/': typeof TenantAuthenticatedDashboardIndexRoute
  '/$tenant/farms/': typeof TenantAuthenticatedFarmsIndexRoute
  '/$tenant/investments/': typeof TenantAuthenticatedInvestmentsIndexRoute
  '/$tenant/notifications/': typeof TenantAuthenticatedNotificationsIndexRoute
  '/$tenant/settings/': typeof TenantAuthenticatedSettingsIndexRoute
  '/$tenant/transactions/': typeof TenantAuthenticatedTransactionsIndexRoute
  '/$tenant/wallet/': typeof TenantAuthenticatedWalletIndexRoute
  '/$tenant/auth/forgot-password/': typeof TenantAuthForgotPasswordIndexRoute
  '/$tenant/auth/reset-password/': typeof TenantAuthResetPasswordIndexRoute
  '/$tenant/auth/sign-in/': typeof TenantAuthSignInIndexRoute
  '/$tenant/auth/sign-up/': typeof TenantAuthSignUpIndexRoute
  '/$tenant/admin/farms/new': typeof TenantAuthenticatedAdminFarmsNewRoute
  '/$tenant/admin/users/$id': typeof TenantAuthenticatedAdminUsersIdRoute
  '/$tenant/farms/$id/invest': typeof TenantAuthenticatedFarmsIdInvestRoute
  '/$tenant/admin/farms/': typeof TenantAuthenticatedAdminFarmsIndexRoute
  '/$tenant/farms/$id/': typeof TenantAuthenticatedFarmsIdIndexRoute
  '/$tenant/admin/farms/$id/analytics': typeof TenantAuthenticatedAdminFarmsIdAnalyticsRoute
  '/$tenant/admin/farms/$id/edit': typeof TenantAuthenticatedAdminFarmsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/$tenant': typeof TenantIndexRoute
  '/$tenant/onboarding': typeof TenantOnboardingRoute
  '/$tenant/privacy': typeof TenantPrivacyRoute
  '/$tenant/support': typeof TenantSupportRoute
  '/$tenant/terms': typeof TenantTermsRoute
  '/super-admin/access': typeof SuperAdminAccessRoute
  '/super-admin/readiness': typeof SuperAdminReadinessRoute
  '/super-admin/tenants': typeof SuperAdminTenantsRoute
  '/super-admin': typeof SuperAdminIndexRoute
  '/$tenant/news': typeof TenantAuthenticatedNewsRoute
  '/$tenant/auth/verify-email': typeof TenantAuthVerifyEmailRoute
  '/$tenant/auth': typeof TenantAuthIndexRoute
  '/$tenant/admin/investors': typeof TenantAuthenticatedAdminInvestorsRoute
  '/$tenant/admin/kyc': typeof TenantAuthenticatedAdminKycRoute
  '/$tenant/admin/payouts': typeof TenantAuthenticatedAdminPayoutsRoute
  '/$tenant/admin/reports': typeof TenantAuthenticatedAdminReportsRoute
  '/$tenant/admin/transactions': typeof TenantAuthenticatedAdminTransactionsRoute
  '/$tenant/farm/$id': typeof TenantAuthenticatedFarmIdRoute
  '/$tenant/investments/$id': typeof TenantAuthenticatedInvestmentsIdRoute
  '/$tenant/payment/callback': typeof TenantAuthenticatedPaymentCallbackRoute
  '/$tenant/settings/notifications': typeof TenantAuthenticatedSettingsNotificationsRoute
  '/$tenant/settings/security': typeof TenantAuthenticatedSettingsSecurityRoute
  '/$tenant/settings/verification': typeof TenantAuthenticatedSettingsVerificationRoute
  '/$tenant/admin': typeof TenantAuthenticatedAdminIndexRoute
  '/$tenant/dashboard': typeof TenantAuthenticatedDashboardIndexRoute
  '/$tenant/farms': typeof TenantAuthenticatedFarmsIndexRoute
  '/$tenant/investments': typeof TenantAuthenticatedInvestmentsIndexRoute
  '/$tenant/notifications': typeof TenantAuthenticatedNotificationsIndexRoute
  '/$tenant/settings': typeof TenantAuthenticatedSettingsIndexRoute
  '/$tenant/transactions': typeof TenantAuthenticatedTransactionsIndexRoute
  '/$tenant/wallet': typeof TenantAuthenticatedWalletIndexRoute
  '/$tenant/auth/forgot-password': typeof TenantAuthForgotPasswordIndexRoute
  '/$tenant/auth/reset-password': typeof TenantAuthResetPasswordIndexRoute
  '/$tenant/auth/sign-in': typeof TenantAuthSignInIndexRoute
  '/$tenant/auth/sign-up': typeof TenantAuthSignUpIndexRoute
  '/$tenant/admin/farms/new': typeof TenantAuthenticatedAdminFarmsNewRoute
  '/$tenant/admin/users/$id': typeof TenantAuthenticatedAdminUsersIdRoute
  '/$tenant/farms/$id/invest': typeof TenantAuthenticatedFarmsIdInvestRoute
  '/$tenant/admin/farms': typeof TenantAuthenticatedAdminFarmsIndexRoute
  '/$tenant/farms/$id': typeof TenantAuthenticatedFarmsIdIndexRoute
  '/$tenant/admin/farms/$id/analytics': typeof TenantAuthenticatedAdminFarmsIdAnalyticsRoute
  '/$tenant/admin/farms/$id/edit': typeof TenantAuthenticatedAdminFarmsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/super-admin': typeof SuperAdminRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/$tenant/_authenticated': typeof TenantAuthenticatedRouteRouteWithChildren
  '/$tenant/auth': typeof TenantAuthRouteRouteWithChildren
  '/$tenant/onboarding': typeof TenantOnboardingRoute
  '/$tenant/privacy': typeof TenantPrivacyRoute
  '/$tenant/support': typeof TenantSupportRoute
  '/$tenant/terms': typeof TenantTermsRoute
  '/super-admin/access': typeof SuperAdminAccessRoute
  '/super-admin/readiness': typeof SuperAdminReadinessRoute
  '/super-admin/tenants': typeof SuperAdminTenantsRoute
  '/$tenant/': typeof TenantIndexRoute
  '/super-admin/': typeof SuperAdminIndexRoute
  '/$tenant/_authenticated/settings': typeof TenantAuthenticatedSettingsRouteRouteWithChildren
  '/$tenant/_authenticated/admin': typeof TenantAuthenticatedAdminRouteWithChildren
  '/$tenant/_authenticated/news': typeof TenantAuthenticatedNewsRoute
  '/$tenant/auth/verify-email': typeof TenantAuthVerifyEmailRoute
  '/$tenant/auth/': typeof TenantAuthIndexRoute
  '/$tenant/_authenticated/admin/investors': typeof TenantAuthenticatedAdminInvestorsRoute
  '/$tenant/_authenticated/admin/kyc': typeof TenantAuthenticatedAdminKycRoute
  '/$tenant/_authenticated/admin/payouts': typeof TenantAuthenticatedAdminPayoutsRoute
  '/$tenant/_authenticated/admin/reports': typeof TenantAuthenticatedAdminReportsRoute
  '/$tenant/_authenticated/admin/transactions': typeof TenantAuthenticatedAdminTransactionsRoute
  '/$tenant/_authenticated/farm/$id': typeof TenantAuthenticatedFarmIdRoute
  '/$tenant/_authenticated/investments/$id': typeof TenantAuthenticatedInvestmentsIdRoute
  '/$tenant/_authenticated/payment/callback': typeof TenantAuthenticatedPaymentCallbackRoute
  '/$tenant/_authenticated/settings/notifications': typeof TenantAuthenticatedSettingsNotificationsRoute
  '/$tenant/_authenticated/settings/security': typeof TenantAuthenticatedSettingsSecurityRoute
  '/$tenant/_authenticated/settings/verification': typeof TenantAuthenticatedSettingsVerificationRoute
  '/$tenant/_authenticated/admin/': typeof TenantAuthenticatedAdminIndexRoute
  '/$tenant/_authenticated/dashboard/': typeof TenantAuthenticatedDashboardIndexRoute
  '/$tenant/_authenticated/farms/': typeof TenantAuthenticatedFarmsIndexRoute
  '/$tenant/_authenticated/investments/': typeof TenantAuthenticatedInvestmentsIndexRoute
  '/$tenant/_authenticated/notifications/': typeof TenantAuthenticatedNotificationsIndexRoute
  '/$tenant/_authenticated/settings/': typeof TenantAuthenticatedSettingsIndexRoute
  '/$tenant/_authenticated/transactions/': typeof TenantAuthenticatedTransactionsIndexRoute
  '/$tenant/_authenticated/wallet/': typeof TenantAuthenticatedWalletIndexRoute
  '/$tenant/auth/forgot-password/': typeof TenantAuthForgotPasswordIndexRoute
  '/$tenant/auth/reset-password/': typeof TenantAuthResetPasswordIndexRoute
  '/$tenant/auth/sign-in/': typeof TenantAuthSignInIndexRoute
  '/$tenant/auth/sign-up/': typeof TenantAuthSignUpIndexRoute
  '/$tenant/_authenticated/admin/farms/new': typeof TenantAuthenticatedAdminFarmsNewRoute
  '/$tenant/_authenticated/admin/users/$id': typeof TenantAuthenticatedAdminUsersIdRoute
  '/$tenant/_authenticated/farms/$id/invest': typeof TenantAuthenticatedFarmsIdInvestRoute
  '/$tenant/_authenticated/admin/farms/': typeof TenantAuthenticatedAdminFarmsIndexRoute
  '/$tenant/_authenticated/farms/$id/': typeof TenantAuthenticatedFarmsIdIndexRoute
  '/$tenant/_authenticated/admin/farms/$id/analytics': typeof TenantAuthenticatedAdminFarmsIdAnalyticsRoute
  '/$tenant/_authenticated/admin/farms/$id/edit': typeof TenantAuthenticatedAdminFarmsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/super-admin'
    | '/auth'
    | '/$tenant'
    | '/$tenant/auth'
    | '/$tenant/onboarding'
    | '/$tenant/privacy'
    | '/$tenant/support'
    | '/$tenant/terms'
    | '/super-admin/access'
    | '/super-admin/readiness'
    | '/super-admin/tenants'
    | '/$tenant/'
    | '/super-admin/'
    | '/$tenant/settings'
    | '/$tenant/admin'
    | '/$tenant/news'
    | '/$tenant/auth/verify-email'
    | '/$tenant/auth/'
    | '/$tenant/admin/investors'
    | '/$tenant/admin/kyc'
    | '/$tenant/admin/payouts'
    | '/$tenant/admin/reports'
    | '/$tenant/admin/transactions'
    | '/$tenant/farm/$id'
    | '/$tenant/investments/$id'
    | '/$tenant/payment/callback'
    | '/$tenant/settings/notifications'
    | '/$tenant/settings/security'
    | '/$tenant/settings/verification'
    | '/$tenant/admin/'
    | '/$tenant/dashboard/'
    | '/$tenant/farms/'
    | '/$tenant/investments/'
    | '/$tenant/notifications/'
    | '/$tenant/settings/'
    | '/$tenant/transactions/'
    | '/$tenant/wallet/'
    | '/$tenant/auth/forgot-password/'
    | '/$tenant/auth/reset-password/'
    | '/$tenant/auth/sign-in/'
    | '/$tenant/auth/sign-up/'
    | '/$tenant/admin/farms/new'
    | '/$tenant/admin/users/$id'
    | '/$tenant/farms/$id/invest'
    | '/$tenant/admin/farms/'
    | '/$tenant/farms/$id/'
    | '/$tenant/admin/farms/$id/analytics'
    | '/$tenant/admin/farms/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/$tenant'
    | '/$tenant/onboarding'
    | '/$tenant/privacy'
    | '/$tenant/support'
    | '/$tenant/terms'
    | '/super-admin/access'
    | '/super-admin/readiness'
    | '/super-admin/tenants'
    | '/super-admin'
    | '/$tenant/news'
    | '/$tenant/auth/verify-email'
    | '/$tenant/auth'
    | '/$tenant/admin/investors'
    | '/$tenant/admin/kyc'
    | '/$tenant/admin/payouts'
    | '/$tenant/admin/reports'
    | '/$tenant/admin/transactions'
    | '/$tenant/farm/$id'
    | '/$tenant/investments/$id'
    | '/$tenant/payment/callback'
    | '/$tenant/settings/notifications'
    | '/$tenant/settings/security'
    | '/$tenant/settings/verification'
    | '/$tenant/admin'
    | '/$tenant/dashboard'
    | '/$tenant/farms'
    | '/$tenant/investments'
    | '/$tenant/notifications'
    | '/$tenant/settings'
    | '/$tenant/transactions'
    | '/$tenant/wallet'
    | '/$tenant/auth/forgot-password'
    | '/$tenant/auth/reset-password'
    | '/$tenant/auth/sign-in'
    | '/$tenant/auth/sign-up'
    | '/$tenant/admin/farms/new'
    | '/$tenant/admin/users/$id'
    | '/$tenant/farms/$id/invest'
    | '/$tenant/admin/farms'
    | '/$tenant/farms/$id'
    | '/$tenant/admin/farms/$id/analytics'
    | '/$tenant/admin/farms/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/super-admin'
    | '/auth'
    | '/$tenant/_authenticated'
    | '/$tenant/auth'
    | '/$tenant/onboarding'
    | '/$tenant/privacy'
    | '/$tenant/support'
    | '/$tenant/terms'
    | '/super-admin/access'
    | '/super-admin/readiness'
    | '/super-admin/tenants'
    | '/$tenant/'
    | '/super-admin/'
    | '/$tenant/_authenticated/settings'
    | '/$tenant/_authenticated/admin'
    | '/$tenant/_authenticated/news'
    | '/$tenant/auth/verify-email'
    | '/$tenant/auth/'
    | '/$tenant/_authenticated/admin/investors'
    | '/$tenant/_authenticated/admin/kyc'
    | '/$tenant/_authenticated/admin/payouts'
    | '/$tenant/_authenticated/admin/reports'
    | '/$tenant/_authenticated/admin/transactions'
    | '/$tenant/_authenticated/farm/$id'
    | '/$tenant/_authenticated/investments/$id'
    | '/$tenant/_authenticated/payment/callback'
    | '/$tenant/_authenticated/settings/notifications'
    | '/$tenant/_authenticated/settings/security'
    | '/$tenant/_authenticated/settings/verification'
    | '/$tenant/_authenticated/admin/'
    | '/$tenant/_authenticated/dashboard/'
    | '/$tenant/_authenticated/farms/'
    | '/$tenant/_authenticated/investments/'
    | '/$tenant/_authenticated/notifications/'
    | '/$tenant/_authenticated/settings/'
    | '/$tenant/_authenticated/transactions/'
    | '/$tenant/_authenticated/wallet/'
    | '/$tenant/auth/forgot-password/'
    | '/$tenant/auth/reset-password/'
    | '/$tenant/auth/sign-in/'
    | '/$tenant/auth/sign-up/'
    | '/$tenant/_authenticated/admin/farms/new'
    | '/$tenant/_authenticated/admin/users/$id'
    | '/$tenant/_authenticated/farms/$id/invest'
    | '/$tenant/_authenticated/admin/farms/'
    | '/$tenant/_authenticated/farms/$id/'
    | '/$tenant/_authenticated/admin/farms/$id/analytics'
    | '/$tenant/_authenticated/admin/farms/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SuperAdminRouteRoute: typeof SuperAdminRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  TenantAuthenticatedRouteRoute: typeof TenantAuthenticatedRouteRouteWithChildren
  TenantAuthRouteRoute: typeof TenantAuthRouteRouteWithChildren
  TenantOnboardingRoute: typeof TenantOnboardingRoute
  TenantPrivacyRoute: typeof TenantPrivacyRoute
  TenantSupportRoute: typeof TenantSupportRoute
  TenantTermsRoute: typeof TenantTermsRoute
  TenantIndexRoute: typeof TenantIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin': {
      id: '/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof SuperAdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/': {
      id: '/super-admin/'
      path: '/'
      fullPath: '/super-admin/'
      preLoaderRoute: typeof SuperAdminIndexRouteImport
      parentRoute: typeof SuperAdminRouteRoute
    }
    '/$tenant/': {
      id: '/$tenant/'
      path: '/$tenant'
      fullPath: '/$tenant/'
      preLoaderRoute: typeof TenantIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/tenants': {
      id: '/super-admin/tenants'
      path: '/tenants'
      fullPath: '/super-admin/tenants'
      preLoaderRoute: typeof SuperAdminTenantsRouteImport
      parentRoute: typeof SuperAdminRouteRoute
    }
    '/super-admin/readiness': {
      id: '/super-admin/readiness'
      path: '/readiness'
      fullPath: '/super-admin/readiness'
      preLoaderRoute: typeof SuperAdminReadinessRouteImport
      parentRoute: typeof SuperAdminRouteRoute
    }
    '/super-admin/access': {
      id: '/super-admin/access'
      path: '/access'
      fullPath: '/super-admin/access'
      preLoaderRoute: typeof SuperAdminAccessRouteImport
      parentRoute: typeof SuperAdminRouteRoute
    }
    '/$tenant/terms': {
      id: '/$tenant/terms'
      path: '/$tenant/terms'
      fullPath: '/$tenant/terms'
      preLoaderRoute: typeof TenantTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$tenant/support': {
      id: '/$tenant/support'
      path: '/$tenant/support'
      fullPath: '/$tenant/support'
      preLoaderRoute: typeof TenantSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$tenant/privacy': {
      id: '/$tenant/privacy'
      path: '/$tenant/privacy'
      fullPath: '/$tenant/privacy'
      preLoaderRoute: typeof TenantPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$tenant/onboarding': {
      id: '/$tenant/onboarding'
      path: '/$tenant/onboarding'
      fullPath: '/$tenant/onboarding'
      preLoaderRoute: typeof TenantOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$tenant/auth': {
      id: '/$tenant/auth'
      path: '/$tenant/auth'
      fullPath: '/$tenant/auth'
      preLoaderRoute: typeof TenantAuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$tenant/_authenticated': {
      id: '/$tenant/_authenticated'
      path: '/$tenant'
      fullPath: '/$tenant'
      preLoaderRoute: typeof TenantAuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$tenant/auth/': {
      id: '/$tenant/auth/'
      path: '/'
      fullPath: '/$tenant/auth/'
      preLoaderRoute: typeof TenantAuthIndexRouteImport
      parentRoute: typeof TenantAuthRouteRoute
    }
    '/$tenant/auth/verify-email': {
      id: '/$tenant/auth/verify-email'
      path: '/verify-email'
      fullPath: '/$tenant/auth/verify-email'
      preLoaderRoute: typeof TenantAuthVerifyEmailRouteImport
      parentRoute: typeof TenantAuthRouteRoute
    }
    '/$tenant/_authenticated/news': {
      id: '/$tenant/_authenticated/news'
      path: '/news'
      fullPath: '/$tenant/news'
      preLoaderRoute: typeof TenantAuthenticatedNewsRouteImport
      parentRoute: typeof TenantAuthenticatedRouteRoute
    }
    '/$tenant/_authenticated/admin': {
      id: '/$tenant/_authenticated/admin'
      path: '/admin'
      fullPath: '/$tenant/admin'
      preLoaderRoute: typeof TenantAuthenticatedAdminRouteImport
      parentRoute: typeof TenantAuthenticatedRouteRoute
    }
    '/$tenant/_authenticated/settings': {
      id: '/$tenant/_authenticated/settings'
      path: '/settings'
      fullPath: '/$tenant/settings'
      preLoaderRoute: typeof TenantAuthenticatedSettingsRouteRouteImport
      parentRoute: typeof TenantAuthenticatedRouteRoute
    }
    '/$tenant/auth/sign-up/': {
      id: '/$tenant/auth/sign-up/'
      path: '/sign-up'
      fullPath: '/$tenant/auth/sign-up/'
      preLoaderRoute: typeof TenantAuthSignUpIndexRouteImport
      parentRoute: typeof TenantAuthRouteRoute
    }
    '/$tenant/auth/sign-in/': {
      id: '/$tenant/auth/sign-in/'
      path: '/sign-in'
      fullPath: '/$tenant/auth/sign-in/'
      preLoaderRoute: typeof TenantAuthSignInIndexRouteImport
      parentRoute: typeof TenantAuthRouteRoute
    }
    '/$tenant/auth/reset-password/': {
      id: '/$tenant/auth/reset-password/'
      path: '/reset-password'
      fullPath: '/$tenant/auth/reset-password/'
      preLoaderRoute: typeof TenantAuthResetPasswordIndexRouteImport
      parentRoute: typeof TenantAuthRouteRoute
    }
    '/$tenant/auth/forgot-password/': {
      id: '/$tenant/auth/forgot-password/'
      path: '/forgot-password'
      fullPath: '/$tenant/auth/forgot-password/'
      preLoaderRoute: typeof TenantAuthForgotPasswordIndexRouteImport
      parentRoute: typeof TenantAuthRouteRoute
    }
    '/$tenant/_authenticated/wallet/': {
      id: '/$tenant/_authenticated/wallet/'
      path: '/wallet'
      fullPath: '/$tenant/wallet/'
      preLoaderRoute: typeof TenantAuthenticatedWalletIndexRouteImport
      parentRoute: typeof TenantAuthenticatedRouteRoute
    }
    '/$tenant/_authenticated/transactions/': {
      id: '/$tenant/_authenticated/transactions/'
      path: '/transactions'
      fullPath: '/$tenant/transactions/'
      preLoaderRoute: typeof TenantAuthenticatedTransactionsIndexRouteImport
      parentRoute: typeof TenantAuthenticatedRouteRoute
    }
    '/$tenant/_authenticated/settings/': {
      id: '/$tenant/_authenticated/settings/'
      path: '/'
      fullPath: '/$tenant/settings/'
      preLoaderRoute: typeof TenantAuthenticatedSettingsIndexRouteImport
      parentRoute: typeof TenantAuthenticatedSettingsRouteRoute
    }
    '/$tenant/_authenticated/notifications/': {
      id: '/$tenant/_authenticated/notifications/'
      path: '/notifications'
      fullPath: '/$tenant/notifications/'
      preLoaderRoute: typeof TenantAuthenticatedNotificationsIndexRouteImport
      parentRoute: typeof TenantAuthenticatedRouteRoute
    }
    '/$tenant/_authenticated/investments/': {
      id: '/$tenant/_authenticated/investments/'
      path: '/investments'
      fullPath: '/$tenant/investments/'
      preLoaderRoute: typeof TenantAuthenticatedInvestmentsIndexRouteImport
      parentRoute: typeof TenantAuthenticatedRouteRoute
    }
    '/$tenant/_authenticated/farms/': {
      id: '/$tenant/_authenticated/farms/'
      path: '/farms'
      fullPath: '/$tenant/farms/'
      preLoaderRoute: typeof TenantAuthenticatedFarmsIndexRouteImport
      parentRoute: typeof TenantAuthenticatedRouteRoute
    }
    '/$tenant/_authenticated/dashboard/': {
      id: '/$tenant/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/$tenant/dashboard/'
      preLoaderRoute: typeof TenantAuthenticatedDashboardIndexRouteImport
      parentRoute: typeof TenantAuthenticatedRouteRoute
    }
    '/$tenant/_authenticated/admin/': {
      id: '/$tenant/_authenticated/admin/'
      path: '/'
      fullPath: '/$tenant/admin/'
      preLoaderRoute: typeof TenantAuthenticatedAdminIndexRouteImport
      parentRoute: typeof TenantAuthenticatedAdminRoute
    }
    '/$tenant/_authenticated/settings/verification': {
      id: '/$tenant/_authenticated/settings/verification'
      path: '/verification'
      fullPath: '/$tenant/settings/verification'
      preLoaderRoute: typeof TenantAuthenticatedSettingsVerificationRouteImport
      parentRoute: typeof TenantAuthenticatedSettingsRouteRoute
    }
    '/$tenant/_authenticated/settings/security': {
      id: '/$tenant/_authenticated/settings/security'
      path: '/security'
      fullPath: '/$tenant/settings/security'
      preLoaderRoute: typeof TenantAuthenticatedSettingsSecurityRouteImport
      parentRoute: typeof TenantAuthenticatedSettingsRouteRoute
    }
    '/$tenant/_authenticated/settings/notifications': {
      id: '/$tenant/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/$tenant/settings/notifications'
      preLoaderRoute: typeof TenantAuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof TenantAuthenticatedSettingsRouteRoute
    }
    '/$tenant/_authenticated/payment/callback': {
      id: '/$tenant/_authenticated/payment/callback'
      path: '/payment/callback'
      fullPath: '/$tenant/payment/callback'
      preLoaderRoute: typeof TenantAuthenticatedPaymentCallbackRouteImport
      parentRoute: typeof TenantAuthenticatedRouteRoute
    }
    '/$tenant/_authenticated/investments/$id': {
      id: '/$tenant/_authenticated/investments/$id'
      path: '/investments/$id'
      fullPath: '/$tenant/investments/$id'
      preLoaderRoute: typeof TenantAuthenticatedInvestmentsIdRouteImport
      parentRoute: typeof TenantAuthenticatedRouteRoute
    }
    '/$tenant/_authenticated/farm/$id': {
      id: '/$tenant/_authenticated/farm/$id'
      path: '/farm/$id'
      fullPath: '/$tenant/farm/$id'
      preLoaderRoute: typeof TenantAuthenticatedFarmIdRouteImport
      parentRoute: typeof TenantAuthenticatedRouteRoute
    }
    '/$tenant/_authenticated/admin/transactions': {
      id: '/$tenant/_authenticated/admin/transactions'
      path: '/transactions'
      fullPath: '/$tenant/admin/transactions'
      preLoaderRoute: typeof TenantAuthenticatedAdminTransactionsRouteImport
      parentRoute: typeof TenantAuthenticatedAdminRoute
    }
    '/$tenant/_authenticated/admin/reports': {
      id: '/$tenant/_authenticated/admin/reports'
      path: '/reports'
      fullPath: '/$tenant/admin/reports'
      preLoaderRoute: typeof TenantAuthenticatedAdminReportsRouteImport
      parentRoute: typeof TenantAuthenticatedAdminRoute
    }
    '/$tenant/_authenticated/admin/payouts': {
      id: '/$tenant/_authenticated/admin/payouts'
      path: '/payouts'
      fullPath: '/$tenant/admin/payouts'
      preLoaderRoute: typeof TenantAuthenticatedAdminPayoutsRouteImport
      parentRoute: typeof TenantAuthenticatedAdminRoute
    }
    '/$tenant/_authenticated/admin/kyc': {
      id: '/$tenant/_authenticated/admin/kyc'
      path: '/kyc'
      fullPath: '/$tenant/admin/kyc'
      preLoaderRoute: typeof TenantAuthenticatedAdminKycRouteImport
      parentRoute: typeof TenantAuthenticatedAdminRoute
    }
    '/$tenant/_authenticated/admin/investors': {
      id: '/$tenant/_authenticated/admin/investors'
      path: '/investors'
      fullPath: '/$tenant/admin/investors'
      preLoaderRoute: typeof TenantAuthenticatedAdminInvestorsRouteImport
      parentRoute: typeof TenantAuthenticatedAdminRoute
    }
    '/$tenant/_authenticated/farms/$id/': {
      id: '/$tenant/_authenticated/farms/$id/'
      path: '/farms/$id'
      fullPath: '/$tenant/farms/$id/'
      preLoaderRoute: typeof TenantAuthenticatedFarmsIdIndexRouteImport
      parentRoute: typeof TenantAuthenticatedRouteRoute
    }
    '/$tenant/_authenticated/admin/farms/': {
      id: '/$tenant/_authenticated/admin/farms/'
      path: '/farms'
      fullPath: '/$tenant/admin/farms/'
      preLoaderRoute: typeof TenantAuthenticatedAdminFarmsIndexRouteImport
      parentRoute: typeof TenantAuthenticatedAdminRoute
    }
    '/$tenant/_authenticated/farms/$id/invest': {
      id: '/$tenant/_authenticated/farms/$id/invest'
      path: '/farms/$id/invest'
      fullPath: '/$tenant/farms/$id/invest'
      preLoaderRoute: typeof TenantAuthenticatedFarmsIdInvestRouteImport
      parentRoute: typeof TenantAuthenticatedRouteRoute
    }
    '/$tenant/_authenticated/admin/users/$id': {
      id: '/$tenant/_authenticated/admin/users/$id'
      path: '/users/$id'
      fullPath: '/$tenant/admin/users/$id'
      preLoaderRoute: typeof TenantAuthenticatedAdminUsersIdRouteImport
      parentRoute: typeof TenantAuthenticatedAdminRoute
    }
    '/$tenant/_authenticated/admin/farms/new': {
      id: '/$tenant/_authenticated/admin/farms/new'
      path: '/farms/new'
      fullPath: '/$tenant/admin/farms/new'
      preLoaderRoute: typeof TenantAuthenticatedAdminFarmsNewRouteImport
      parentRoute: typeof TenantAuthenticatedAdminRoute
    }
    '/$tenant/_authenticated/admin/farms/$id/edit': {
      id: '/$tenant/_authenticated/admin/farms/$id/edit'
      path: '/farms/$id/edit'
      fullPath: '/$tenant/admin/farms/$id/edit'
      preLoaderRoute: typeof TenantAuthenticatedAdminFarmsIdEditRouteImport
      parentRoute: typeof TenantAuthenticatedAdminRoute
    }
    '/$tenant/_authenticated/admin/farms/$id/analytics': {
      id: '/$tenant/_authenticated/admin/farms/$id/analytics'
      path: '/farms/$id/analytics'
      fullPath: '/$tenant/admin/farms/$id/analytics'
      preLoaderRoute: typeof TenantAuthenticatedAdminFarmsIdAnalyticsRouteImport
      parentRoute: typeof TenantAuthenticatedAdminRoute
    }
  }
}

interface SuperAdminRouteRouteChildren {
  SuperAdminAccessRoute: typeof SuperAdminAccessRoute
  SuperAdminReadinessRoute: typeof SuperAdminReadinessRoute
  SuperAdminTenantsRoute: typeof SuperAdminTenantsRoute
  SuperAdminIndexRoute: typeof SuperAdminIndexRoute
}

const SuperAdminRouteRouteChildren: SuperAdminRouteRouteChildren = {
  SuperAdminAccessRoute: SuperAdminAccessRoute,
  SuperAdminReadinessRoute: SuperAdminReadinessRoute,
  SuperAdminTenantsRoute: SuperAdminTenantsRoute,
  SuperAdminIndexRoute: SuperAdminIndexRoute,
}

const SuperAdminRouteRouteWithChildren = SuperAdminRouteRoute._addFileChildren(
  SuperAdminRouteRouteChildren,
)

interface TenantAuthenticatedSettingsRouteRouteChildren {
  TenantAuthenticatedSettingsNotificationsRoute: typeof TenantAuthenticatedSettingsNotificationsRoute
  TenantAuthenticatedSettingsSecurityRoute: typeof TenantAuthenticatedSettingsSecurityRoute
  TenantAuthenticatedSettingsVerificationRoute: typeof TenantAuthenticatedSettingsVerificationRoute
  TenantAuthenticatedSettingsIndexRoute: typeof TenantAuthenticatedSettingsIndexRoute
}

const TenantAuthenticatedSettingsRouteRouteChildren: TenantAuthenticatedSettingsRouteRouteChildren =
  {
    TenantAuthenticatedSettingsNotificationsRoute:
      TenantAuthenticatedSettingsNotificationsRoute,
    TenantAuthenticatedSettingsSecurityRoute:
      TenantAuthenticatedSettingsSecurityRoute,
    TenantAuthenticatedSettingsVerificationRoute:
      TenantAuthenticatedSettingsVerificationRoute,
    TenantAuthenticatedSettingsIndexRoute:
      TenantAuthenticatedSettingsIndexRoute,
  }

const TenantAuthenticatedSettingsRouteRouteWithChildren =
  TenantAuthenticatedSettingsRouteRoute._addFileChildren(
    TenantAuthenticatedSettingsRouteRouteChildren,
  )

interface TenantAuthenticatedAdminRouteChildren {
  TenantAuthenticatedAdminInvestorsRoute: typeof TenantAuthenticatedAdminInvestorsRoute
  TenantAuthenticatedAdminKycRoute: typeof TenantAuthenticatedAdminKycRoute
  TenantAuthenticatedAdminPayoutsRoute: typeof TenantAuthenticatedAdminPayoutsRoute
  TenantAuthenticatedAdminReportsRoute: typeof TenantAuthenticatedAdminReportsRoute
  TenantAuthenticatedAdminTransactionsRoute: typeof TenantAuthenticatedAdminTransactionsRoute
  TenantAuthenticatedAdminIndexRoute: typeof TenantAuthenticatedAdminIndexRoute
  TenantAuthenticatedAdminFarmsNewRoute: typeof TenantAuthenticatedAdminFarmsNewRoute
  TenantAuthenticatedAdminUsersIdRoute: typeof TenantAuthenticatedAdminUsersIdRoute
  TenantAuthenticatedAdminFarmsIndexRoute: typeof TenantAuthenticatedAdminFarmsIndexRoute
  TenantAuthenticatedAdminFarmsIdAnalyticsRoute: typeof TenantAuthenticatedAdminFarmsIdAnalyticsRoute
  TenantAuthenticatedAdminFarmsIdEditRoute: typeof TenantAuthenticatedAdminFarmsIdEditRoute
}

const TenantAuthenticatedAdminRouteChildren: TenantAuthenticatedAdminRouteChildren =
  {
    TenantAuthenticatedAdminInvestorsRoute:
      TenantAuthenticatedAdminInvestorsRoute,
    TenantAuthenticatedAdminKycRoute: TenantAuthenticatedAdminKycRoute,
    TenantAuthenticatedAdminPayoutsRoute: TenantAuthenticatedAdminPayoutsRoute,
    TenantAuthenticatedAdminReportsRoute: TenantAuthenticatedAdminReportsRoute,
    TenantAuthenticatedAdminTransactionsRoute:
      TenantAuthenticatedAdminTransactionsRoute,
    TenantAuthenticatedAdminIndexRoute: TenantAuthenticatedAdminIndexRoute,
    TenantAuthenticatedAdminFarmsNewRoute:
      TenantAuthenticatedAdminFarmsNewRoute,
    TenantAuthenticatedAdminUsersIdRoute: TenantAuthenticatedAdminUsersIdRoute,
    TenantAuthenticatedAdminFarmsIndexRoute:
      TenantAuthenticatedAdminFarmsIndexRoute,
    TenantAuthenticatedAdminFarmsIdAnalyticsRoute:
      TenantAuthenticatedAdminFarmsIdAnalyticsRoute,
    TenantAuthenticatedAdminFarmsIdEditRoute:
      TenantAuthenticatedAdminFarmsIdEditRoute,
  }

const TenantAuthenticatedAdminRouteWithChildren =
  TenantAuthenticatedAdminRoute._addFileChildren(
    TenantAuthenticatedAdminRouteChildren,
  )

interface TenantAuthenticatedRouteRouteChildren {
  TenantAuthenticatedSettingsRouteRoute: typeof TenantAuthenticatedSettingsRouteRouteWithChildren
  TenantAuthenticatedAdminRoute: typeof TenantAuthenticatedAdminRouteWithChildren
  TenantAuthenticatedNewsRoute: typeof TenantAuthenticatedNewsRoute
  TenantAuthenticatedFarmIdRoute: typeof TenantAuthenticatedFarmIdRoute
  TenantAuthenticatedInvestmentsIdRoute: typeof TenantAuthenticatedInvestmentsIdRoute
  TenantAuthenticatedPaymentCallbackRoute: typeof TenantAuthenticatedPaymentCallbackRoute
  TenantAuthenticatedDashboardIndexRoute: typeof TenantAuthenticatedDashboardIndexRoute
  TenantAuthenticatedFarmsIndexRoute: typeof TenantAuthenticatedFarmsIndexRoute
  TenantAuthenticatedInvestmentsIndexRoute: typeof TenantAuthenticatedInvestmentsIndexRoute
  TenantAuthenticatedNotificationsIndexRoute: typeof TenantAuthenticatedNotificationsIndexRoute
  TenantAuthenticatedTransactionsIndexRoute: typeof TenantAuthenticatedTransactionsIndexRoute
  TenantAuthenticatedWalletIndexRoute: typeof TenantAuthenticatedWalletIndexRoute
  TenantAuthenticatedFarmsIdInvestRoute: typeof TenantAuthenticatedFarmsIdInvestRoute
  TenantAuthenticatedFarmsIdIndexRoute: typeof TenantAuthenticatedFarmsIdIndexRoute
}

const TenantAuthenticatedRouteRouteChildren: TenantAuthenticatedRouteRouteChildren =
  {
    TenantAuthenticatedSettingsRouteRoute:
      TenantAuthenticatedSettingsRouteRouteWithChildren,
    TenantAuthenticatedAdminRoute: TenantAuthenticatedAdminRouteWithChildren,
    TenantAuthenticatedNewsRoute: TenantAuthenticatedNewsRoute,
    TenantAuthenticatedFarmIdRoute: TenantAuthenticatedFarmIdRoute,
    TenantAuthenticatedInvestmentsIdRoute:
      TenantAuthenticatedInvestmentsIdRoute,
    TenantAuthenticatedPaymentCallbackRoute:
      TenantAuthenticatedPaymentCallbackRoute,
    TenantAuthenticatedDashboardIndexRoute:
      TenantAuthenticatedDashboardIndexRoute,
    TenantAuthenticatedFarmsIndexRoute: TenantAuthenticatedFarmsIndexRoute,
    TenantAuthenticatedInvestmentsIndexRoute:
      TenantAuthenticatedInvestmentsIndexRoute,
    TenantAuthenticatedNotificationsIndexRoute:
      TenantAuthenticatedNotificationsIndexRoute,
    TenantAuthenticatedTransactionsIndexRoute:
      TenantAuthenticatedTransactionsIndexRoute,
    TenantAuthenticatedWalletIndexRoute: TenantAuthenticatedWalletIndexRoute,
    TenantAuthenticatedFarmsIdInvestRoute:
      TenantAuthenticatedFarmsIdInvestRoute,
    TenantAuthenticatedFarmsIdIndexRoute: TenantAuthenticatedFarmsIdIndexRoute,
  }

const TenantAuthenticatedRouteRouteWithChildren =
  TenantAuthenticatedRouteRoute._addFileChildren(
    TenantAuthenticatedRouteRouteChildren,
  )

interface TenantAuthRouteRouteChildren {
  TenantAuthVerifyEmailRoute: typeof TenantAuthVerifyEmailRoute
  TenantAuthIndexRoute: typeof TenantAuthIndexRoute
  TenantAuthForgotPasswordIndexRoute: typeof TenantAuthForgotPasswordIndexRoute
  TenantAuthResetPasswordIndexRoute: typeof TenantAuthResetPasswordIndexRoute
  TenantAuthSignInIndexRoute: typeof TenantAuthSignInIndexRoute
  TenantAuthSignUpIndexRoute: typeof TenantAuthSignUpIndexRoute
}

const TenantAuthRouteRouteChildren: TenantAuthRouteRouteChildren = {
  TenantAuthVerifyEmailRoute: TenantAuthVerifyEmailRoute,
  TenantAuthIndexRoute: TenantAuthIndexRoute,
  TenantAuthForgotPasswordIndexRoute: TenantAuthForgotPasswordIndexRoute,
  TenantAuthResetPasswordIndexRoute: TenantAuthResetPasswordIndexRoute,
  TenantAuthSignInIndexRoute: TenantAuthSignInIndexRoute,
  TenantAuthSignUpIndexRoute: TenantAuthSignUpIndexRoute,
}

const TenantAuthRouteRouteWithChildren = TenantAuthRouteRoute._addFileChildren(
  TenantAuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SuperAdminRouteRoute: SuperAdminRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  TenantAuthenticatedRouteRoute: TenantAuthenticatedRouteRouteWithChildren,
  TenantAuthRouteRoute: TenantAuthRouteRouteWithChildren,
  TenantOnboardingRoute: TenantOnboardingRoute,
  TenantPrivacyRoute: TenantPrivacyRoute,
  TenantSupportRoute: TenantSupportRoute,
  TenantTermsRoute: TenantTermsRoute,
  TenantIndexRoute: TenantIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
